name: php-framework
recipe: lemp
config:
  via: nginx
  config: 
     extensions: pdo_pgsql
     vhosts: .lando/nginx.conf
  php: '8.2'
services: 
  postgres:
   portforward: true
   type: postgres:15
